name: whisper_flutter_new
description: Use whisper.cpp models implementation for Android and iOS
version: 1.0.1
repository: https://github.com/xuegao-tzx/whisper_flutter_new
issue_tracker: https://github.com/xuegao-tzx/whisper_flutter_new/issues
homepage: https://pub.dev/packages/whisper_flutter_new

platforms:
  android:
  ios:
  macos:

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  ffi: ^2.1.2
  flutter:
    sdk: flutter
  freezed_annotation: any
  json_annotation: any
  path_provider: ^2.1.3
  plugin_platform_interface: ^2.1.8


dev_dependencies:
  build_runner: ^2.4.11
  flutter_lints: any
  ffigen: ^12.0.0
  freezed: any
  json_serializable: any

flutter:
  plugin:
    platforms:
      android:
        ffiPlugin: true
      ios:
        ffiPlugin: true
      macos:
        ffiPlugin: true